trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v0.0.7

jobs:
- template: job--pre-commit.yml@asottile
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [pypy, py27, py35]
    os: linux
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [pypy3, py36, py37]
    os: linux
    name_postfix: _nocover
    coverage: False
